const PLUS_TRANSPORTE_DIA   = 1.03;
const PLUS_FESTIVO_HORA     = 3.5;
const PLUS_PENOSIDAD_HORA   = 4;
const PLUS_NOCTURNIDAD_HORA = 3.5;

module.exports = { PLUS_TRANSPORTE_DIA, PLUS_FESTIVO_HORA, PLUS_PENOSIDAD_HORA, PLUS_NOCTURNIDAD_HORA };
